import type { Route } from ".react-router/types/app/+types/root";
import { Box, IconButton, Link, Stack, Typography } from "@mui/material";
import Navbar from "~/cash-flow/cash-flow-analysis/components/navbar";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import InfoOutlineIcon from "@mui/icons-material/InfoOutline";
import { useState } from "react";
import InfoDialog from "~/components/info-dialog/info-dialog";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Cash Flow Analysis" },
    { name: "description", content: "Cash Flow Analysis" },
  ];
}

interface AnalysisItem {
  title: string;
  description: string;
  value: string;
  trend: "up" | "down";
  fullDescription: string;
}

const data: AnalysisItem[] = [
  {
    title: "Property Income Coverage Ratio",
    description: "Rental Income / Operating Expenses",
    value: "1.25",
    trend: "up",
    fullDescription:
      "This metric indicates the ability of a property to cover its operating expenses with its rental income. A ratio above 1 means the property generates enough income to cover its expenses.",
  },
  {
    title: "Cash on Cash Return",
    description: "Anual Cash Flow / Total Cash Invested",
    value: "0.10",
    trend: "up",
    fullDescription:
      "Measures the annual pre-tax cash flow generated by an investment property relative to the total cash invested. Expressed as a percentage, it helps evaluate the cash yield of the investment.",
  },
  {
    title: "Net Yield",
    description: "Net Operating Income / Property Value",
    value: "0.08",
    trend: "down",
    fullDescription:
      "Represents the annual net income generated by a property as a percentage of its total value. It accounts for all income and expenses, providing a clear picture of overall profitability.",
  },
];

const CashFlowAnalysis = () => {
  const [isOpenInfoDialog, setIsOpenInfoDialog] = useState(false);
  const [selectedItem, setSelectedItem] = useState<AnalysisItem | null>(null);

  const handleOpenInfoDialog = (item: AnalysisItem) => {
    setSelectedItem(item);
    setIsOpenInfoDialog(true);
  };

  const handleCloseInfoDialog = () => {
    setIsOpenInfoDialog(false);
    setSelectedItem(null);
  };

  return (
    <>
      <Box>
        <Navbar />
        <Box p={2}>
          {data.map((item, index) => (
            <Box
              key={index}
              sx={{
                position: "relative",
                backgroundColor: "var(--bg-color-secondary)",
                borderRadius: 2,
                border: "1px solid var(--border-color)",
                px: 2,
                py: 2,
                mb: 2,
              }}
            >
              <Box
                display="flex"
                justifyContent="space-between"
                alignItems="flex-end"
              >
                <Box>
                  <Typography fontSize={"1.4rem"} mb={0.5}>
                    {item.title}
                  </Typography>
                  <Typography color="var(--text-color-secondary)">
                    {item.description}
                  </Typography>
                </Box>
                <Box display="flex" alignItems="center" gap={1}>
                  <Typography
                    fontSize={"2.4rem"}
                    fontWeight={700}
                    lineHeight={1}
                  >
                    {item.value}
                  </Typography>
                  <Box
                    display="flex"
                    alignItems="center"
                    gap={0.5}
                    sx={{
                      color:
                        item.trend === "up"
                          ? "var(--system--green-300)"
                          : "var(--system--red-300)",
                      backgroundColor:
                        item.trend === "up"
                          ? "rgba(var(--system--green-300-alpha), 0.2)"
                          : "rgba(var(--system--red-300-alpha), 0.2)",
                      border:
                        item.trend === "up"
                          ? "1px solid rgba(var(--system--green-300-alpha), 0.2)"
                          : "1px solid rgba(var(--system--red-300-alpha), 0.2)",
                      borderRadius: 0.5,
                      py: 0.2,
                      px: 0.5,
                    }}
                  >
                    {item.trend === "up" ? (
                      <TrendingUpIcon
                        sx={{
                          fontSize: "1.2rem",
                        }}
                      />
                    ) : (
                      <TrendingUpIcon
                        sx={{
                          fontSize: "1.2rem",
                          transform: "rotate(180deg)",
                        }}
                      />
                    )}
                  </Box>
                </Box>
              </Box>
              <IconButton
                onClick={() => handleOpenInfoDialog(item)}
                sx={{
                  backgroundColor: "rgba(var(--accent--primary-1-alpha), 0.3)",
                  color: "var(--text-color-secondary)",
                  "&:hover": {
                    backgroundColor: "rgba(var(--accent--primary-1-alpha), 1)",
                    color: "white",
                  },
                  position: "absolute",
                  top: "-13px",
                  right: "-13px",
                  padding: 0.5,
                }}
              >
                <InfoOutlineIcon
                  sx={{
                    fontSize: "2rem",
                  }}
                />
              </IconButton>
            </Box>
          ))}
        </Box>
      </Box>
      {selectedItem && (
        <InfoDialog
          title={selectedItem.title}
          description={selectedItem.fullDescription}
          open={isOpenInfoDialog}
          onClose={handleCloseInfoDialog}
        />
      )}
    </>
  );
};

export default CashFlowAnalysis;
