import type { Route } from ".react-router/types/app/+types/root";
import { Box, Typography } from "@mui/material";
import Navbar from "~/cash-flow/cash-flow-analysis/components/navbar";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import { useState } from "react";
import InfoDialog from "~/components/info-dialog";
import ButtonIcon from "~/components/button-icon";
import Card from "~/components/card";
import AnalysisCard from "~/cash-flow/cash-flow-analysis/components/analysis-card";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Cash Flow Analysis" },
    { name: "description", content: "Cash Flow Analysis" },
  ];
}

interface AnalysisItem {
  title: string;
  description: string;
  value: string;
  trend: "up" | "down";
  fullDescription: string;
}

const data: AnalysisItem[] = [
  {
    title: "Property Income Coverage Ratio",
    description: "Rental Income / Operating Expenses",
    value: "1.25",
    trend: "up",
    fullDescription:
      "This metric indicates the ability of a property to cover its operating expenses with its rental income. A ratio above 1 means the property generates enough income to cover its expenses.",
  },
  {
    title: "Cash on Cash Return",
    description: "Anual Cash Flow / Total Cash Invested",
    value: "0.10",
    trend: "up",
    fullDescription:
      "Measures the annual pre-tax cash flow generated by an investment property relative to the total cash invested. Expressed as a percentage, it helps evaluate the cash yield of the investment.",
  },
  {
    title: "Net Yield",
    description: "Net Operating Income / Property Value",
    value: "0.08",
    trend: "down",
    fullDescription:
      "Represents the annual net income generated by a property as a percentage of its total value. It accounts for all income and expenses, providing a clear picture of overall profitability.",
  },
];

const CashFlowAnalysis = () => {
  const [isOpenInfoDialog, setIsOpenInfoDialog] = useState(false);
  const [selectedItem, setSelectedItem] = useState<AnalysisItem | null>(null);

  const handleOpenInfoDialog = (item: AnalysisItem) => {
    setSelectedItem(item);
    setIsOpenInfoDialog(true);
  };

  const handleCloseInfoDialog = () => {
    setIsOpenInfoDialog(false);
  };

  return (
    <>
      <Box>
        <Navbar />
        <Box p={2}>
          {data.map((item, index) => (
            <AnalysisCard
              sx={{ mb: 2 }}
              key={index}
              item={item}
              onClick={() => handleOpenInfoDialog(item)}
            />
          ))}
        </Box>
      </Box>
      {selectedItem && (
        <InfoDialog
          title={selectedItem.title}
          shortDescription={selectedItem.fullDescription}
          open={isOpenInfoDialog}
          onClose={handleCloseInfoDialog}
          formula="Net Cash Flow = Operating Cash Flow + Investing Cash Flow + Financing Cash Flow"
          longDescription="Cash flow is the movement of money into or out of a business, project, or financial product. It is a key indicator of financial health. Positive cash flow means more money is coming in than going out, while negative cash flow indicates the opposite. Understanding cash flow helps in making informed decisions about investments, expenses, and growth strategies."
          youtubeUrl="https://www.youtube.com/embed/HRwK3cbkywk?si=XflznV34c5F-q1EF"
        />
      )}
    </>
  );
};

export default CashFlowAnalysis;
